var schools = [
	{ "Name": "10 KCD", "Number": "853" },
	{ "Name": "Akademisk Studenterkursus og HF", "Number": "645" },
	{ "Name": "Allerød Gymnasium", "Number": "51" },
	{ "Name": "Allikelund Gymnasium", "Number": "768" },
	{ "Name": "Alssundgymnasiet Sønderborg", "Number": "161" },
	{ "Name": "AU - Institut for odontologi og oral sundhed", "Number": "550" },
	{ "Name": "Aurehøj Gymnasium", "Number": "1" },
	{ "Name": "Bagsværd Kostskole og Gymnasium", "Number": "3" },
	{ "Name": "Birkerød Gymnasium og HF", "Number": "52" },
	{ "Name": "Bjerringbro Gymnasium", "Number": "266" },
	{ "Name": "Borupgaard Gymnasium", "Number": "37" },
	{ "Name": "Brøndby Gymnasium", "Number": "38" },
	{ "Name": "Brønderslev Gymnasium og HF", "Number": "281" },
	{ "Name": "Campus Bornholm EUD", "Number": "132" },
	{ "Name": "Campus Bornholm GYM", "Number": "137" },
	{ "Name": "Campus Bornholm Sprogcenter", "Number": "139" },
	{ "Name": "Campus Kujalleq", "Number": "364" },
	{ "Name": "Christianshavns Gymnasium", "Number": "5" },
	{ "Name": "Det frie Gymnasium", "Number": "40" },
	{ "Name": "Det Kristne Gymnasium", "Number": "228" },
	{ "Name": "Det Naturvidenskabelige Gymnasium på HRS, Valby", "Number": "765" },
	{ "Name": "Deutsches Gymnasium für Nordschleswig", "Number": "162" },
	{ "Name": "Dronninglund Gymnasium", "Number": "292" },
	{ "Name": "DTU", "Number": "788" },
	{ "Name": "Edutasia", "Number": "545" },
	{ "Name": "Egedal Gymnasium & HF", "Number": "62" },
	{ "Name": "Egaa Gymnasium", "Number": "256" },
	{ "Name": "Erhvervsskolerne Aars, hhx og htx", "Number": "529" },
	{ "Name": "Erhvervsskolerne Aars, KHF", "Number": "534" },
	{ "Name": "Esbjerg Gymnasium", "Number": "181" },
	{ "Name": "Espergærde Gymnasium og HF", "Number": "57" },
	{ "Name": "EUC Nord - AMU - Frederikshavn", "Number": "321" },
	{ "Name": "EUC Nord - EAU - Hjørring", "Number": "322" },
	{ "Name": "EUC Nord - EUD - Frederikshavn", "Number": "323" },
	{ "Name": "EUC Nord - HES - Hestkærvej", "Number": "318" },
	{ "Name": "EUC Nord - HTX - Frederikshavn", "Number": "319" },
	{ "Name": "EUC Nord - HTX - Hjørring", "Number": "320" },
	{ "Name": "EUC Nordvestsjælland", "Number": "769" },
	{ "Name": "EUC Sjælland - HTX Køge", "Number": "677" },
	{ "Name": "EUC Sjælland - HTX Næstved", "Number": "678" },
	{ "Name": "European School Copenhagen Upper Secondary", "Number": "548" },
	{ "Name": "Falkonergårdens Gymnasium og HF", "Number": "7" },
	{ "Name": "Fjerritslev Gymnasium", "Number": "291" },
	{ "Name": "Folkekirkens Uddannelses- og Videnscenter", "Number": "568" },
	{ "Name": "Fredericia Gymnasium", "Number": "201" },
	{ "Name": "Frederiksberg Gymnasium", "Number": "8" },
	{ "Name": "Frederiksberg HF-kursus", "Number": "351" },
	{ "Name": "Frederiksborg Gymnasium og hf", "Number": "54" },
	{ "Name": "Frederikshavn Gymnasium", "Number": "282" },
	{ "Name": "Frederikshavn Handelsskole", "Number": "917" },
	{ "Name": "Frederikssund Gymnasium", "Number": "55" },
	{ "Name": "Frederiksværk Gymnasium og HF", "Number": "60" },
	{ "Name": "Friskolen på Røsnæs", "Number": "528" },
	{ "Name": "Faaborg Gymnasium", "Number": "150" },
	{ "Name": "Gammel Hellerup Gymnasium", "Number": "9" },
	{ "Name": "Gefion Gymnasium", "Number": "17" },
	{ "Name": "Gentofte HF", "Number": "365" },
	{ "Name": "Gentofte Studenterkursus", "Number": "304" },
	{ "Name": "Gladsaxe Gymnasium", "Number": "11" },
	{ "Name": "Grenaa Gymnasium", "Number": "241" },
	{ "Name": "Greve Gymnasium", "Number": "71" },
	{ "Name": "Gribskov Gymnasium", "Number": "61" },
	{ "Name": "GUX - Sisimiut", "Number": "539" },
	{ "Name": "GUX Nuuk", "Number": "354" },
	{ "Name": "GU-Aasiaat", "Number": "362" },
	{ "Name": "H.C. Ørsted Gymnasiet - Ballerup", "Number": "680" },
	{ "Name": "H.C. Ørsted Gymnasiet - Frederiksberg", "Number": "679" },
	{ "Name": "H.C. Ørsted Gymnasiet - Lyngby", "Number": "681" },
	{ "Name": "Haderslev Katedralskole", "Number": "163" },
	{ "Name": "Handelsfagskolen", "Number": "720" },
	{ "Name": "Handelsgymnasiet Vestfyn", "Number": "511" },
	{ "Name": "Hasseris Gymnasium", "Number": "283" },
	{ "Name": "Helsingør Gymnasium", "Number": "53" },
	{ "Name": "Herlev Gymnasium og HF", "Number": "12" },
	{ "Name": "Herlufsholm Skole", "Number": "111" },
	{ "Name": "Herning Gymnasium", "Number": "221" },
	{ "Name": "Herning HF og VUC", "Number": "355" },
	{ "Name": "HF & VUC København Syd, Amager afd.", "Number": "454" },
	{ "Name": "HF & VUC København Syd, Hvidovre afd.", "Number": "455" },
	{ "Name": "HF & VUC Nordsjælland Helsingør", "Number": "532" },
	{ "Name": "HF & VUC Nordsjælland Hillerød", "Number": "533" },
	{ "Name": "HF-Centret Efterslægten", "Number": "6" },
	{ "Name": "Himmelev Gymnasium", "Number": "75" },
	{ "Name": "Hindholm STX", "Number": "82" },
	{ "Name": "Hjørring Gymnasium / STX og HF", "Number": "284" },
	{ "Name": "Holstebro Gymnasium og HF", "Number": "222" },
	{ "Name": "Horsens Gymnasium", "Number": "209" },
	{ "Name": "Horsens Statsskole", "Number": "202" },
	{ "Name": "Hovedstadens Kristne Gymnasium", "Number": "280" },
	{ "Name": "HTX Roskilde", "Number": "523" },
	{ "Name": "Hvidovre Gymnasium og HF", "Number": "2" },
	{ "Name": "Høje Taastrup Private Gymnasium", "Number": "345" },
	{ "Name": "Høje-Taastrup Gymnasium", "Number": "36" },
	{ "Name": "Høng Gymnasium og HF", "Number": "97" },
	{ "Name": "IBC Fredericia Middelfart", "Number": "942" },
	{ "Name": "IBC HF og VUC Fredericia", "Number": "944" },
	{ "Name": "IBC Innovationsfabrikken", "Number": "945" },
	{ "Name": "IBC Kolding", "Number": "943" },
	{ "Name": "IBC Aabenraa", "Number": "941" },
	{ "Name": "Ikast-Brande Gymnasium", "Number": "223" },
	{ "Name": "Imarsiornermik Ilinniarfik Nuuk", "Number": "516" },
	{ "Name": "Imarsiornermik Ilinniarfik Paamiut", "Number": "573" },
	{ "Name": "Ingrid Jespersens Gymnasieskole", "Number": "13" },
	{ "Name": "INUILI", "Number": "521" },
	{ "Name": "Johannesskolens Gymnasium", "Number": "16" },
	{ "Name": "Kalundborg Gymnasium og HF", "Number": "92" },
	{ "Name": "Kolding Gymnasium", "Number": "203" },
	{ "Name": "Kriminalforsorgen, UCB", "Number": "88" },
	{ "Name": "Københavns Idrætsefterskole", "Number": "403" },
	{ "Name": "Københavns Private Gymnasium", "Number": "484" },
	{ "Name": "Københavns VUC", "Number": "530" },
	{ "Name": "Københavns åbne Gymnasium", "Number": "32" },
	{ "Name": "Køge Gymnasium", "Number": "72" },
	{ "Name": "Køge Handelsgymnasium - EUX", "Number": "138" },
	{ "Name": "Køge Handelsgymnasium - HHX", "Number": "131" },
	{ "Name": "Køge Private Realskole", "Number": "932" },
	{ "Name": "Learnmark Horsens Handelsgymnasium HHX", "Number": "306" },
	{ "Name": "Learnmark Horsens Teknisk Gymnasium HTX", "Number": "305" },
	{ "Name": "Læreruddannelsen i Silkeborg", "Number": "526" },
	{ "Name": "Læreruddannelsen i Skive", "Number": "877" },
	{ "Name": "Mariagerfjord Gymnasium", "Number": "285" },
	{ "Name": "Maribo Gymnasium", "Number": "112" },
	{ "Name": "Marie Kruses Skole", "Number": "58" },
	{ "Name": "Marselisborg Gymnasium", "Number": "243" },
	{ "Name": "Mercantec, Bygge- og anlæg EUD/AMU", "Number": "576" },
	{ "Name": "Mercantec, Midtbyens Gymnasium", "Number": "577" },
	{ "Name": "Mercantec, teknisk og merkantil EUD/AMU", "Number": "575" },
	{ "Name": "Michael Skolen", "Number": "270" },
	{ "Name": "Middelfart Gymnasium", "Number": "141" },
	{ "Name": "Miðnámsskúlin í Suðuroy", "Number": "225" },
	{ "Name": "Midtfyns Gymnasium", "Number": "955" },
	{ "Name": "Midtjysk Erhvervskøreskole og Uddannelsescenter", "Number": "544" },
	{ "Name": "Midtsjællands Gymnasium", "Number": "91" },
	{ "Name": "Morsø Gymnasium", "Number": "261" },
	{ "Name": "Mulernes Legatskole", "Number": "143" },
	{ "Name": "Munkensdam Gymnasium", "Number": "207" },
	{ "Name": "N. Zahles Gymnasieskole", "Number": "19" },
	{ "Name": "Nakskov Gymnasium og HF", "Number": "402" },
	{ "Name": "NEXT - Baltorp Gymnasium", "Number": "48" },
	{ "Name": "NEXT - EUX", "Number": "517" },
	{ "Name": "NEXT - Københavns Mediegymnasium", "Number": "520" },
	{ "Name": "NEXT - Sukkertoppen Gymnasium", "Number": "518" },
	{ "Name": "NEXT - Sydkysten Gymnasium", "Number": "44" },
	{ "Name": "NEXT - Vestskoven Gymnasium", "Number": "43" },
	{ "Name": "NEXT - Vibenshus Gymnasium", "Number": "519" },
	{ "Name": "Niels Steensens Gymnasium", "Number": "20" },
	{ "Name": "Niuernermik Ilinniarfik, Nuuk", "Number": "988" },
	{ "Name": "Nordfyns Gymnasium", "Number": "513" },
	{ "Name": "Nordsjællands Grundskole og Gymnasium", "Number": "63" },
	{ "Name": "Nyborg Gymnasium", "Number": "144" },
	{ "Name": "Nykøbing Katedralskole", "Number": "114" },
	{ "Name": "Nærum Gymnasium", "Number": "31" },
	{ "Name": "Næstved Gymnasium og HF", "Number": "115" },
	{ "Name": "Nørre Gymnasium", "Number": "21" },
	{ "Name": "Nørresundby Gymnasium og HF", "Number": "287" },
	{ "Name": "Odder Gymnasium", "Number": "254" },
	{ "Name": "Odense Katedralskole", "Number": "600" },
	{ "Name": "Odense Tekniske Gymnasium", "Number": "857" },
	{ "Name": "Odsherreds Gymnasium", "Number": "96" },
	{ "Name": "Ordrup Gymnasium", "Number": "22" },
	{ "Name": "Oure Kostgymnasium", "Number": "152" },
	{ "Name": "Paderup Gymnasium", "Number": "253" },
	{ "Name": "Paul Petersens Idrætsinstitut", "Number": "135" },
	{ "Name": "Peqqissaanermik Ilinniarfik, Nuuk", "Number": "353" },
	{ "Name": "Perorsaanermik Ilinniarfik SPS", "Number": "515" },
	{ "Name": "Pharmakon", "Number": "547" },
	{ "Name": "Randers Statsskole", "Number": "245" },
	{ "Name": "Ribe Katedralskole", "Number": "184" },
	{ "Name": "Risskov Gymnasium", "Number": "246" },
	{ "Name": "Rosborg Gymnasium og hf", "Number": "204" },
	{ "Name": "Roskilde Gymnasium", "Number": "73" },
	{ "Name": "Roskilde Katedralskole", "Number": "76" },
	{ "Name": "Roskilde Tekniske Skole - EUD", "Number": "522" },
	{ "Name": "Rudolf Steiner Skolen Kvistgård", "Number": "658" },
	{ "Name": "Rungsted Gymnasium", "Number": "59" },
	{ "Name": "Rybners Gymnasium", "Number": "182" },
	{ "Name": "Rysensteen Gymnasium", "Number": "23" },
	{ "Name": "Rødkilde Gymnasium", "Number": "205" },
	{ "Name": "Rødovre Gymnasium", "Number": "24" },
	{ "Name": "Rønde Gymnasium", "Number": "247" },
	{ "Name": "Sankt Annæ Gymnasium", "Number": "25" },
	{ "Name": "Sankt Petri Gymnasium", "Number": "489" },
	{ "Name": "Scania Danmark", "Number": "542" },
	{ "Name": "Sct. Knuds Gymnasium", "Number": "590" },
	{ "Name": "SDU, Teoretisk Pædagogikum", "Number": "500" },
	{ "Name": "Silkeborg Gymnasium", "Number": "248" },
	{ "Name": "Skanderborg Gymnasium", "Number": "249" },
	{ "Name": "Skanderborg-Odder Center for Uddannelse EUD/EUX", "Number": "558" },
	{ "Name": "Skanderborg-Odder Center for Uddannelse HF & VUC", "Number": "560" },
	{ "Name": "Skanderborg-Odder Center for Uddannelse HHX", "Number": "563" },
	{ "Name": "Skanderborg-Odder Center for Uddannelse HTX SOCU", "Number": "569" },
	{ "Name": "Skive College", "Number": "562" },
	{ "Name": "Skive Gymnasium & HF", "Number": "262" },
	{ "Name": "Skolerne i Oure Sport & Performance", "Number": "153" },
	{ "Name": "Slagelse Gymnasium", "Number": "93" },
	{ "Name": "Slotshaven Gymnasium", "Number": "557" },
	{ "Name": "Solrød Gymnasium", "Number": "74" },
	{ "Name": "Sorø Akademis Skole", "Number": "94" },
	{ "Name": "Stenhus Gymnasium", "Number": "95" },
	{ "Name": "Struer Statsgymnasium", "Number": "224" },
	{ "Name": "Studenterkurset i Sønderjylland", "Number": "307" },
	{ "Name": "Støvring Gymnasium", "Number": "286" },
	{ "Name": "Svendborg Gymnasium", "Number": "477" },
	{ "Name": "Sønderborg Statsskole", "Number": "164" },
	{ "Name": "Søværnets Officersskole", "Number": "531" },
	{ "Name": "Teknikimik Ilinniarfik", "Number": "865" },
	{ "Name": "Teknisk Gymnasium Sønderjylland", "Number": "427" },
	{ "Name": "Th. Langs HF & VUC", "Number": "360" },
	{ "Name": "Thisted Gymnasium STX og HF", "Number": "263" },
	{ "Name": "Thy - Mors HF & VUC", "Number": "700" },
	{ "Name": "Tradium, Mariagerfjord", "Number": "567" },
	{ "Name": "Tradium, Rådmands Boulevard", "Number": "571" },
	{ "Name": "Tradium, Vester Allé", "Number": "572" },
	{ "Name": "Trafikskolen", "Number": "543" },
	{ "Name": "Tørring Gymnasium", "Number": "208" },
	{ "Name": "Tårnby Gymnasium", "Number": "30" },
	{ "Name": "UCH Handelsgymnasium", "Number": "508" },
	{ "Name": "UCH Teknisk Gymnasium", "Number": "509" },
	{ "Name": "UCVest", "Number": "782" },
	{ "Name": "UNORD Frederikssund", "Number": "238" },
	{ "Name": "UNORD Helsingør", "Number": "237" },
	{ "Name": "UNORD Hillerød Handelsgymnasium og Handelsskole", "Number": "240" },
	{ "Name": "UNORD Hillerød Teknisk Gymnasium", "Number": "236" },
	{ "Name": "UNORD Hillerød Tekniske Erhvervsuddannelser", "Number": "235" },
	{ "Name": "UNORD Kursuscenteret", "Number": "244" },
	{ "Name": "UNORD Lyngby", "Number": "234" },
	{ "Name": "UNORD Lyngby Erhvervsuddannelser", "Number": "239" },
	{ "Name": "Varde Gymnasium og HF-kursus", "Number": "185" },
	{ "Name": "Varde Handelsskole og Handelsgymnasium", "Number": "902" },
	{ "Name": "Vejen Gymnasium og HF", "Number": "186" },
	{ "Name": "Vejle Handelsskole", "Number": "565" },
	{ "Name": "Vejlefjordskolen", "Number": "206" },
	{ "Name": "Vestegnen HF & VUC", "Number": "420" },
	{ "Name": "Vestegnen HF & VUC, Albertslund", "Number": "421" },
	{ "Name": "Vestfyns Gymnasium", "Number": "148" },
	{ "Name": "Vesthimmerlands Gymnasium og HF", "Number": "288" },
	{ "Name": "Vestjysk Gymnasium Tarm", "Number": "78" },
	{ "Name": "Viborg Gymnasium og HF", "Number": "264" },
	{ "Name": "Viborg Handelsgymnasium", "Number": "555" },
	{ "Name": "Viborg Katedralskole", "Number": "265" },
	{ "Name": "Viborg Tekniske Gymnasium", "Number": "556" },
	{ "Name": "Viby Gymnasium", "Number": "250" },
	{ "Name": "Vidar Skolen", "Number": "259" },
	{ "Name": "Viden Djurs - VID Gymnasier", "Number": "641" },
	{ "Name": "Virum Gymnasium", "Number": "33" },
	{ "Name": "Vordingborg Gymnasium & HF", "Number": "116" },
	{ "Name": "VUC Lyngby", "Number": "537" },
	{ "Name": "VUF - VoksenUddannelsescenter Frederiksberg", "Number": "380" },
	{ "Name": "ZBC EUD", "Number": "157" },
	{ "Name": "ZBC Næstved", "Number": "156" },
	{ "Name": "ZBC Ringsted", "Number": "158" },
	{ "Name": "ZBC Ringsted EUD", "Number": "159" },
	{ "Name": "ZBC Slagelse", "Number": "165" },
	{ "Name": "ZBC Vordingborg", "Number": "160" },
	{ "Name": "ZBC Vordingborg EUD", "Number": "155" },
	{ "Name": "Øregård Gymnasium", "Number": "34" },
	{ "Name": "Ørestad Gymnasium", "Number": "26" },
	{ "Name": "AABC - Aarhus Business College Campus Sønderhøj", "Number": "123" },
	{ "Name": "AABC - Aarhus Handelsgymnasium Vejlby Centervej", "Number": "121" },
	{ "Name": "AABC - Aarhus Handelsgymnasium Viemosevej", "Number": "122" },
	{ "Name": "Aabenraa Statsskole", "Number": "166" },
	{ "Name": "Aalborg Handelsskole - Saxogade", "Number": "551" },
	{ "Name": "Aalborg Handelsskole - Turøgade", "Number": "552" },
	{ "Name": "Aalborg Katedralskole", "Number": "289" },
	{ "Name": "Aalborg Tekniske Gymnasium", "Number": "524" },
	{ "Name": "Aalborghus Gymnasium", "Number": "290" },
	{ "Name": "Århus Akademi", "Number": "311" },
	{ "Name": "AARHUS GYMNASIUM", "Number": "242" },
	{ "Name": "Aarhus Katedralskole", "Number": "251" },
	{ "Name": "Aarhus Private Gymnasium", "Number": "627" }
]

// Schools Select Load
var selectElem = document.getElementById("schoolId");

for (var i = 0; i < schools.length; i++) {
	var obj = schools[i];
	var option = document.createElement("option");

	option.text = obj.Name;
	option.value = obj.Number;
	selectElem.add(option);
}